#############################################################################
# Makefile for building: kiss-skeleton
# Generated by qmake (2.01a) (Qt 4.8.1) on: Sun Apr 8 03:45:11 2012
# Project:  kiss-skeleton.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile kiss-skeleton.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt/mkspecs/linux-g++-64 -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include/QtOpenGL -I/usr/include -Iglm-0.9.2.7 -I/usr/X11R6/include -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1,--sort-common,--as-needed,-z,relro,--hash-style=gnu -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -L/usr/X11R6/lib64 -lGLEW -lQtOpenGL -lQtGui -lQtCore -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = glwidget.cpp \
		qtmain.cpp \
		window.cpp \
		Arcball.cpp \
		kiss-skeleton.cpp \
		zgfx.cpp moc_glwidget.cpp \
		moc_window.cpp
OBJECTS       = glwidget.o \
		qtmain.o \
		window.o \
		Arcball.o \
		kiss-skeleton.o \
		zgfx.o \
		moc_glwidget.o \
		moc_window.o
DIST          = /usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/common/gcc-base.conf \
		/usr/share/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt/mkspecs/common/g++-base.conf \
		/usr/share/qt/mkspecs/common/g++-unix.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/release.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/opengl.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		kiss-skeleton.pro
QMAKE_TARGET  = kiss-skeleton
DESTDIR       = 
TARGET        = kiss-skeleton

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: kiss-skeleton.pro  /usr/share/qt/mkspecs/linux-g++-64/qmake.conf /usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/common/gcc-base.conf \
		/usr/share/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt/mkspecs/common/g++-base.conf \
		/usr/share/qt/mkspecs/common/g++-unix.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/release.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/opengl.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtOpenGL.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile kiss-skeleton.pro
/usr/share/qt/mkspecs/common/unix.conf:
/usr/share/qt/mkspecs/common/linux.conf:
/usr/share/qt/mkspecs/common/gcc-base.conf:
/usr/share/qt/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt/mkspecs/common/g++-base.conf:
/usr/share/qt/mkspecs/common/g++-unix.conf:
/usr/share/qt/mkspecs/qconfig.pri:
/usr/share/qt/mkspecs/modules/qt_phonon.pri:
/usr/share/qt/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt/mkspecs/features/qt_functions.prf:
/usr/share/qt/mkspecs/features/qt_config.prf:
/usr/share/qt/mkspecs/features/exclusive_builds.prf:
/usr/share/qt/mkspecs/features/default_pre.prf:
/usr/share/qt/mkspecs/features/release.prf:
/usr/share/qt/mkspecs/features/default_post.prf:
/usr/share/qt/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt/mkspecs/features/warn_on.prf:
/usr/share/qt/mkspecs/features/qt.prf:
/usr/share/qt/mkspecs/features/unix/opengl.prf:
/usr/share/qt/mkspecs/features/unix/thread.prf:
/usr/share/qt/mkspecs/features/moc.prf:
/usr/share/qt/mkspecs/features/resources.prf:
/usr/share/qt/mkspecs/features/uic.prf:
/usr/share/qt/mkspecs/features/yacc.prf:
/usr/share/qt/mkspecs/features/lex.prf:
/usr/share/qt/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtOpenGL.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile kiss-skeleton.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/kiss-skeleton1.0.0 || $(MKDIR) .tmp/kiss-skeleton1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/kiss-skeleton1.0.0/ && $(COPY_FILE) --parents glwidget.h window.h Arcball.h kiss-skeleton.h zgfx.h .tmp/kiss-skeleton1.0.0/ && $(COPY_FILE) --parents glwidget.cpp qtmain.cpp window.cpp Arcball.cpp kiss-skeleton.cpp zgfx.cpp .tmp/kiss-skeleton1.0.0/ && (cd `dirname .tmp/kiss-skeleton1.0.0` && $(TAR) kiss-skeleton1.0.0.tar kiss-skeleton1.0.0 && $(COMPRESS) kiss-skeleton1.0.0.tar) && $(MOVE) `dirname .tmp/kiss-skeleton1.0.0`/kiss-skeleton1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/kiss-skeleton1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_glwidget.cpp moc_window.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_glwidget.cpp moc_window.cpp
moc_glwidget.cpp: Arcball.h \
		zgfx.h \
		glwidget.h
	/usr/bin/moc $(DEFINES) $(INCPATH) glwidget.h -o moc_glwidget.cpp

moc_window.cpp: window.h
	/usr/bin/moc $(DEFINES) $(INCPATH) window.h -o moc_window.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

glwidget.o: glwidget.cpp glwidget.h \
		Arcball.h \
		zgfx.h \
		kiss-skeleton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glwidget.o glwidget.cpp

qtmain.o: qtmain.cpp window.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtmain.o qtmain.cpp

window.o: window.cpp glwidget.h \
		Arcball.h \
		zgfx.h \
		window.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o window.o window.cpp

Arcball.o: Arcball.cpp Arcball.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Arcball.o Arcball.cpp

kiss-skeleton.o: kiss-skeleton.cpp kiss-skeleton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kiss-skeleton.o kiss-skeleton.cpp

zgfx.o: zgfx.cpp zgfx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zgfx.o zgfx.cpp

moc_glwidget.o: moc_glwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_glwidget.o moc_glwidget.cpp

moc_window.o: moc_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_window.o moc_window.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/doc/qt/examples/opengl/hellogl/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/doc/qt/examples/opengl/hellogl/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/usr/share/doc/qt/examples/opengl/hellogl/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/usr/share/doc/qt/examples/opengl/hellogl/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/share/doc/qt/examples/opengl/hellogl/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/doc/qt/examples/opengl/hellogl/ 


install_sources: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/doc/qt/examples/opengl/hellogl/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/doc/qt/examples/opengl/hellogl/ 
	-$(INSTALL_FILE) /home/zack/programming/kiss-skeleton/glwidget.cpp $(INSTALL_ROOT)/usr/share/doc/qt/examples/opengl/hellogl/
	-$(INSTALL_FILE) /home/zack/programming/kiss-skeleton/qtmain.cpp $(INSTALL_ROOT)/usr/share/doc/qt/examples/opengl/hellogl/
	-$(INSTALL_FILE) /home/zack/programming/kiss-skeleton/window.cpp $(INSTALL_ROOT)/usr/share/doc/qt/examples/opengl/hellogl/
	-$(INSTALL_FILE) /home/zack/programming/kiss-skeleton/Arcball.cpp $(INSTALL_ROOT)/usr/share/doc/qt/examples/opengl/hellogl/
	-$(INSTALL_FILE) /home/zack/programming/kiss-skeleton/kiss-skeleton.cpp $(INSTALL_ROOT)/usr/share/doc/qt/examples/opengl/hellogl/
	-$(INSTALL_FILE) /home/zack/programming/kiss-skeleton/zgfx.cpp $(INSTALL_ROOT)/usr/share/doc/qt/examples/opengl/hellogl/
	-$(INSTALL_FILE) /home/zack/programming/kiss-skeleton/glwidget.h $(INSTALL_ROOT)/usr/share/doc/qt/examples/opengl/hellogl/
	-$(INSTALL_FILE) /home/zack/programming/kiss-skeleton/window.h $(INSTALL_ROOT)/usr/share/doc/qt/examples/opengl/hellogl/
	-$(INSTALL_FILE) /home/zack/programming/kiss-skeleton/Arcball.h $(INSTALL_ROOT)/usr/share/doc/qt/examples/opengl/hellogl/
	-$(INSTALL_FILE) /home/zack/programming/kiss-skeleton/kiss-skeleton.h $(INSTALL_ROOT)/usr/share/doc/qt/examples/opengl/hellogl/
	-$(INSTALL_FILE) /home/zack/programming/kiss-skeleton/zgfx.h $(INSTALL_ROOT)/usr/share/doc/qt/examples/opengl/hellogl/


uninstall_sources:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/doc/qt/examples/opengl/hellogl/glwidget.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/doc/qt/examples/opengl/hellogl/qtmain.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/doc/qt/examples/opengl/hellogl/window.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/doc/qt/examples/opengl/hellogl/Arcball.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/doc/qt/examples/opengl/hellogl/kiss-skeleton.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/doc/qt/examples/opengl/hellogl/zgfx.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/doc/qt/examples/opengl/hellogl/glwidget.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/doc/qt/examples/opengl/hellogl/window.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/doc/qt/examples/opengl/hellogl/Arcball.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/doc/qt/examples/opengl/hellogl/kiss-skeleton.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/doc/qt/examples/opengl/hellogl/zgfx.h
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/doc/qt/examples/opengl/hellogl/ 


install:  install_target install_sources  FORCE

uninstall: uninstall_target uninstall_sources   FORCE

FORCE:

